### ISSUE TITLE
Unable to delete package automatically

### ISSUE THREAD

**Issue by seagle0128** [zenspider/package#9]
Debugger entered--Lisp error: (wrong-type-argument listp cl-struct-package-desc)
  package-version-join(cl-struct-package-desc)
  package-delete-by-name(ag)
  mapc(package-delete-by-name (ag))
  package-cleanup((ac-inf-ruby ac-js2 ...))
  package-manifest(ac-inf-ruby ac-js2 ace-jump-mode ...)
  eval-buffer()  ; Reading at buffer position 5170

**Comment by YellowApple** [comment]
Just a heads up that this is indeed broken in Emacs 24.3 (which is unfortunately the latest available by default in Slackware 14.1, though 24.4 has hit Slackware-current and can probably be installed using the -current SlackBuild).

A workaround for now is to just override package-cleanup by shoving `(defun package-cleanup (packages) ())` into one's `.emacs` (having to override a function in order to shut off a behavior that's likely controversial - since not everyone (myself included) wants non-manifested packages to be automatically deleted - seems silly, but whatever).

**Comment by zenspider** [comment]
@YellowApple if you can come up with a patch that works for you, I can try to meld it in so it works for all of us.
